module.exports.moment = require("moment");
module.exports.jwt = require("jsonwebtoken");
module.exports.cookie = require('cookie');
module.exports.uid = require('uid');
module.exports.bcrypt = require("bcrypt");
module.exports.dotenv= require('dotenv')
module.exports.useragent = require('useragent')
module.exports.db = require('../database/connect')
module.exports.fileUpload = require('express-fileupload');
module.exports.escapeHtml = require('escape-html');
